### ISSUE TITLE
Git submodule fails

### ISSUE THREAD

**Issue by trinytron** [flexiblepower/fpai-examples#2]
"git submodule update" fails, it seems that repo hosted at https://github.com/flexiblepower/fpai-shared-config.git is no longer existing...

Could you fix that please ?

**Comment by wilcowijbrandi** [comment]
You are completely right, thanks for pointing this out!
I will fix this, but it might take some time...
In the mean time you could take look at the fpai-apps repository (https://github.com/flexiblepower/fpai-apps). The simulated appliances in there should also be fairly easy to understand. Let me know if you run into trouble!

**Comment by wilcowijbrandi** [comment]
The submodule issues has been resolved, but I am still not satisfied with the code in this repository. I'll open a new issue soon.
